export const jobData = [
  {
    id: '1',
    title: 'UI / UX Designer',
    description: 'The User Experience Designer position exists to create compelling and digital user experience through excellent design...',
    location: 'New York',
    type: 'Full-time',
    salary: '₹50,000 - ₹60,000',
    level: 'Senior Level',
    experience: 'Min. 3 Years',
  },
  {
    id: '2',
    title: 'Front End Developer',
    description: 'The Front End Developer will work on the client-side of web applications, creating responsive and dynamic user interfaces...',
    location: 'San Francisco',
    type: 'Full-time',
    salary: '₹60,000 - ₹70,000',
    level: 'Mid-Level',
    experience: 'Min. 2 Years',
  },
  {
    id: '3',
    title: 'Back End Developer',
    description: 'The Back End Developer will work on server-side logic and database management, ensuring a seamless connection between server and users...',
    location: 'Los Angeles',
    type: 'Full-time',
    salary: '₹65,000 - ₹75,000',
    level: 'Mid-Level',
    experience: 'Min. 3 Years',
  },
  {
    id: '4',
    title: 'Data Scientist',
    description: 'The Data Scientist will analyze and interpret complex data to help companies make informed decisions...',
    location: 'Chicago',
    type: 'Full-time',
    salary: '₹70,000 - ₹80,000',
    level: 'Senior Level',
    experience: 'Min. 4 Years',
  },
  {
    id: '5',
    title: 'Product Manager',
    description: 'The Product Manager will oversee the development and delivery of product offerings, ensuring they meet market needs and company goals...',
    location: 'Seattle',
    type: 'Full-time',
    salary: '₹75,000 - ₹85,000',
    level: 'Senior Level',
    experience: 'Min. 5 Years',
  },
  {
    id: '6',
    title: 'Digital Marketing Specialist',
    description: 'The Digital Marketing Specialist will develop and execute digital marketing strategies to drive online traffic and engagement...',
    location: 'Austin',
    type: 'Part-time',
    salary: '₹40,000 - ₹50,000',
    level: 'Junior Level',
    experience: 'Min. 1 Year',
  },
  {
    id: '7',
    title: 'Graphic Designer',
    description: 'The Graphic Designer will create visual content to communicate messages through digital and print media...',
    location: 'San Diego',
    type: 'Freelance',
    salary: '₹30,000 - ₹40,000',
    level: 'Mid-Level',
    experience: 'Min. 2 Years',
  },
  {
    id: '8',
    title: 'Software Engineer',
    description: 'The Software Engineer will develop and maintain software applications, ensuring they are efficient, reliable, and scalable...',
    location: 'Boston',
    type: 'Full-time',
    salary: '₹70,000 - ₹80,000',
    level: 'Senior Level',
    experience: 'Min. 3 Years',
  },
  {
    id: '9',
    title: 'System Administrator',
    description: 'The System Administrator will manage and support IT infrastructure, ensuring all systems are running smoothly and securely...',
    location: 'Atlanta',
    type: 'Contract',
    salary: '₹55,000 - ₹65,000',
    level: 'Mid-Level',
    experience: 'Min. 2 Years',
  },
  {
    id: '10',
    title: 'Content Writer',
    description: 'The Content Writer will create engaging and informative content for websites, blogs, and social media...',
    location: 'Miami',
    type: 'Part-time',
    salary: '₹35,000 - ₹45,000',
    level: 'Junior Level',
    experience: 'Min. 1 Year',
  },
  {
    id: '11',
    title: 'Sales Manager',
    description: 'The Sales Manager will lead and manage a sales team, develop strategies to meet sales targets, and drive business growth...',
    location: 'Philadelphia',
    type: 'Full-time',
    salary: '₹65,000 - ₹75,000',
    level: 'Senior Level',
    experience: 'Min. 4 Years',
  },
  {
    id: '12',
    title: 'Network Engineer',
    description: 'The Network Engineer will design, implement, and maintain network infrastructure to ensure reliable connectivity and performance...',
    location: 'Denver',
    type: 'Full-time',
    salary: '₹60,000 - ₹70,000',
    level: 'Mid-Level',
    experience: 'Min. 2 Years',
  },
];
