export const jobNiches = [
  "Software Development",
  "Data Science",
  "Digital Marketing",
  "Cybersecurity",
  "Project Management",
  "Graphic Design",
  "Content Creation",
  "Financial Analysis",
  "Customer Service",
  "Human Resources",
  "Sales",
  "Healthcare",
  "Education and Training",
  "Legal Services",
  "Engineering",
  "Product Management",
  "Business Analysis",
  "Social Media Management",
  "IT Support",
  "Supply Chain Management",
];